-- src/main/resources/db/migration/V1__create_audit_logs_table.sql
-- Flyway migration to create audit_logs table for PostgreSQL

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT NOT NULL,
    action_type VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id BIGINT NOT NULL,
    details TEXT,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

-- Indexes to speed common queries
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_id ON audit_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type_id ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs("timestamp");